### ISSUE TITLE
Can we encode with DL URL?

### ISSUE THREAD

**Issue by wordlesswind** [akiver/csgo-sharecode#23]
Hi akiver, I have some questions about it.
This project use matchInfo to encoding sharecode.
Can we encode with DL URL?
I often dedicate Overwatch Demo DL URL with wireshark to observe the banned state of the suspect.
Today I find your project on there.
So I have the above question.

**Comment by akiver** [comment]
Hi, AFAIK this is not possible to get a share code only from the demo's download URL, you need a MatchInfo message.

**Comment by wordlesswind** [comment]
Ok, thank you for telling me this.
